const CREATE_BOOK = 'CREATE_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const CHANGE_FILTER = 'CHANGE_FILTER';
const SAVE_BOOK = 'SAVE_BOOK';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOK_SUCCESS';
export {
  CREATE_BOOK, REMOVE_BOOK, CHANGE_FILTER, SAVE_BOOK, FETCH_BOOKS_SUCCESS,
};
